cc_binary(
    name = "AoC2021_11",
    srcs = ["AoC2021_11.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aocd:aocd",
    ],
)

