cc_binary(
    name = "AoC2016_13",
    srcs = ["AoC2016_13.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aoc/graph:aoc_graph",
        "//src/main/cpp/aocd:aocd",
    ],
)

