cc_binary(
    name = "AoC2017_03",
    srcs = ["AoC2017_03.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/geometry:aoc_geometry",
        "//src/main/cpp/aocd:aocd",
    ],
)

