cc_binary(
    name = "AoC2021_13",
    srcs = ["AoC2021_13.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aoc/geometry:aoc_geometry",
        "//src/main/cpp/aoc/ocr:aoc_ocr",
        "//src/main/cpp/aocd:aocd",
    ],
)

