cc_library(
    name = "aoc_ocr",
    srcs = ["ocr.cpp"],
    hdrs = ["ocr.hpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
    ],
    visibility = ["//visibility:public"],
)
