cc_binary(
    name = "AoC2017_21",
    srcs = ["AoC2017_21.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aocd:aocd",
    ],
)

