cc_binary(
    name = "AoC2022_09",
    srcs = ["AoC2022_09.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/geometry:aoc_geometry",
        "//src/main/cpp/aocd:aocd",
    ],
)

