cc_binary(
    name = "AoC2015_04",
    srcs = ["AoC2015_04.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/md5:aoc_md5",
        "//src/main/cpp/aocd:aocd",
    ],
)

