cc_binary(
    name = "AoC2016_08",
    srcs = ["AoC2016_08.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aoc/ocr:aoc_ocr",
        "//src/main/cpp/aocd:aocd",
    ],
)

