cc_binary(
    name = "AoC2017_11",
    srcs = ["AoC2017_11.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/geometry3d:aoc_geometry3d",
        "//src/main/cpp/aocd:aocd",
    ],
)

