cc_binary(
    name = "AoC2015_06",
    srcs = ["AoC2015_06.cpp"],
    deps = [
        "//src/main/cpp/aoc:aoc",
        "//src/main/cpp/aoc/grid:aoc_grid",
        "//src/main/cpp/aocd:aocd",
    ],
)

